#ifndef OPENCVUTILITY_GLOBAL_HPP
#define OPENCVUTILITY_GLOBAL_HPP() 1

#include <QtCore/qglobal.h>

#if defined(OPENCVUTILITY_LIBRARY)
#  define OPENCVUTILITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENCVUTILITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENCVUTILITY_GLOBAL_HPP
